defaults:
    path:     /hello/{name}
    defaults: { _controller: FillinHomeBundle:Default:index }

_homework5:
      path:   /homework5/{number}/{multiplier}
      defaults: { _controller: FillinHomeBundle:Home:home}